version: '3.9'
services:
  cumple-app:
    image: sanatorio-cumpleanos:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cumple-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./src/baileys_auth:/app/src/baileys_auth
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
